# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_X86_CPU_RESCTRL2)		+= alloc.o
obj-$(CONFIG_X86_CPU_RESCTRL2)		+= rdt_monitor.o
obj-$(CONFIG_X86_CPU_RESCTRL2)		+= rdt_mbm_adjust.o

obj-$(CONFIG_X86_RDT_L3_CAT)		+= rdt_l3_cat.o
obj-$(CONFIG_X86_RDT_L3_MBA)		+= rdt_l3_mba.o

obj-$(CONFIG_X86_RDT_LLC_OCCUPANCY)	+= rdt_llc_occupancy.o
obj-$(CONFIG_X86_RDT_TOTAL_BYTES)	+= rdt_mbm_total_bytes.o

obj-$(CONFIG_X86_RDT_L3_IO)		+= rdt_l3_io.o

obj-$(CONFIG_X86_RDT_SHOW_IDS)		+= rdt_show_ids.o
