# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_X86_CPU_RESCTRL2)		+= alloc.o
obj-$(CONFIG_X86_CPU_RESCTRL2)		+= rdt_monitor.o

obj-$(CONFIG_X86_RDT_L3_CAT)		+= rdt_l3_cat.o
obj-$(CONFIG_X86_RDT_L3_MBA)		+= rdt_l3_mba.o
