# SPDX-License-Identifier: GPL-2.0

ccflags-y += -DDEFAULT_SYMBOL_NAMESPACE=RESCTRL

obj-$(CONFIG_RESCTRL2_FS) += cpu.o
obj-$(CONFIG_RESCTRL2_FS) += directory.o
obj-$(CONFIG_RESCTRL2_FS) += domain.o
obj-$(CONFIG_RESCTRL2_FS) += info.o
obj-$(CONFIG_RESCTRL2_FS) += kernfs.o
obj-$(CONFIG_RESCTRL2_FS) += locking.o
obj-$(CONFIG_RESCTRL2_FS) += mode.o
obj-$(CONFIG_RESCTRL2_FS) += monitor.o
obj-$(CONFIG_RESCTRL2_FS) += resources.o
obj-$(CONFIG_RESCTRL2_FS) += root.o
obj-$(CONFIG_RESCTRL2_FS) += schemata.o
obj-$(CONFIG_RESCTRL2_FS) += tasks.o

obj-$(CONFIG_PROC_CPU_RESCTRL) += procfs.o
