# SPDX-License-Identifier: GPL-2.0

ccflags-y += -DDEFAULT_SYMBOL_NAMESPACE=RESCTRL

ccflags-y += -DDEFAULT_SYMBOL_NAMESPACE=RESCTRL

obj-$(CONFIG_RESCTRL2_FS) += locking.o
obj-$(CONFIG_RESCTRL2_FS) += root.o

obj-$(CONFIG_X86_CPU_RESCTRL2) += arch/x86/
